---
title: "Global Population Exposure to Volcanoes"
author: "Cris Cunha"
date: "2 July 2017"
output: 
  ioslides_presentation: 
    smaller: yes
runtime: shiny
---

## Introduction

Historically, volcanoes are a key source of natural disasters. Several organisations constantly monitor volcanoes around the globe to understand the risk to humans in locations where volcanoes exist.

The humanitarian data exchange (https://data.humdata.org/) is an initiative created by the United Nations to make available geolocation data related to several humanitarian factors, including natural hazards. 

A web app has been developed to display geolocation information on volcanoes around the globe. The app focuses on quantifying the PEI (Population Exposure Index) to volcanoes, which is a scale 1-10 that classifies each volcano (active and inactive) against the proability of exposure to humans. Several factors constitute the PEI, including:

- Population density vs. proximity to the volcano
- Ability to recover/evacuate in a timely manner
- Level of activity
- Geological history
- Probability of eruption

The dataset can be found on http://data.hdx.rwlabs.org/dataset/volcano-population-exposure-index-gvm/



## Motivation

The web app developed has multiple uses and it is designed to cater for the general population and researchers. Some of the key drivers for the app are:

- Ability to locate active and inactive volcanoes in the desired geolocation
- Visible data including name, region, PEI and activity for each volcano around the world
- Filter visibility based on the level of PEI desired
- Understand level of population exposure for a given region

## Population Exposure to Volcanoes Web App

```{r echo=FALSE, message=FALSE, warning=FALSE}
library(shiny)
library(leaflet)
library(dplyr)
shinyApp(
  
  ui=fluidPage(
  
  titlePanel("Population Exposure to Volcanoes Around the World"),
  
  sidebarLayout(
    sidebarPanel(
      sliderInput("pei",
                  "Population Exposure Index (PE = 1 low, PE = 10 high):",
                  min = 1,
                  max = 10,
                  value = c(2,10)),
      h6("1) Select the range you want of the Exposure index in the slider above."), 
      h6("2) Navigate interactively by clicking on the clusters located at the map."),
      h6(" 3) Hover over each volcano to obtain information."),
      h6(" 4) Active volcanos are shown in green and inactive in red")
                  
    ),
    mainPanel(
      leafletOutput("map")
    )
  )
),

server=function(input, output, clientData, session){

 data<- download.file("http://data.hdx.rwlabs.org/dataset/volcano-population-exposure-index-gvm/resource_download/e3b1ecf0-ec47-49f7-9011-6bbb7403ef6d", destfile="volcanoes.csv")
 data<-read.csv("volcanoes.csv")
 names<-data$V_Name
 pal <- colorFactor(
   palette = "Set1",
   domain = data$H_active)

  updateSliderInput(session, "pei", min = min(data$PEI), max = max(data$PEI))

  filteredData <- reactive({
    data[data$PEI >= input$pei[1] & data$PEI <= input$pei[2],]
  })

  output$map <- renderLeaflet({
    leaflet(data) %>%
      addTiles() %>%
      fitBounds(~min(Longitude), ~min(Latitude), 
                ~max(Longitude), ~max(Latitude)) %>%
    addLegend("topright",pal=pal,values=data$H_active,title="Is the Volcano Active?" ,opacity=1)
  })
  
  observe({
    
    leafletProxy("map", data = filteredData()) %>%
      clearShapes() %>% 
      clearPopups() %>%
      clearMarkerClusters() %>%
      clearMarkers() %>%
      addCircleMarkers(lng=~Longitude, lat=~Latitude,clusterOptions=markerClusterOptions(),
                       label=paste("Name:",data$V_Name,"|","Country:",data$Country,"|","Region:",data$Subregion,"|","PEI:",data$PEI),color=~pal(data$H_active),radius=10)
    

  }
)
}
)
```

## Want to know more?

Web app can be found on  https://ccunha85.shinyapps.io/global_population_exposure_index_to_volcanoes/

Thank you!